import {
  ArrowRight,
  CheckCircle,
  Copy,
  Linkedin,
  Loader2,
  MessageSquare,
  RefreshCw,
  Send,
  Search,
  UserCheck,
  Zap,
  BarChart,
  Home,
  LogOut,
  Settings,
  Sparkles,
  User,
  Users,
  AlertCircle,
  Calendar,
  Clock,
  Edit,
  Info,
  MoreHorizontal,
  Pause,
  Play,
  Plus,
  TrendingUp,
  Download,
  ExternalLink,
  ThumbsUp,
  XCircle,
  Shield,
  Key,
  Lock,
  ClipboardCopy,
  ArrowLeft,
  Briefcase,
  Building,
  Filter,
  MapPin,
  X,
  ArrowUpRight,
  ChevronRight,
  FileText,
  Lightbulb,
  Wand2,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  linkedIn: Linkedin,
  arrowRight: ArrowRight,
  checkCircle: CheckCircle,
  copy: Copy,
  messageSquare: MessageSquare,
  refreshCw: RefreshCw,
  send: Send,
  search: Search,
  userCheck: UserCheck,
  zap: Zap,
  barChart: BarChart,
  home: Home,
  logOut: LogOut,
  settings: Settings,
  sparkles: Sparkles,
  user: User,
  users: Users,
  alertCircle: AlertCircle,
  calendar: Calendar,
  clock: Clock,
  edit: Edit,
  info: Info,
  moreHorizontal: MoreHorizontal,
  pause: Pause,
  play: Play,
  plus: Plus,
  trendingUp: TrendingUp,
  download: Download,
  externalLink: ExternalLink,
  thumbsUp: ThumbsUp,
  xCircle: XCircle,
  shield: Shield,
  key: Key,
  lock: Lock,
  clipboardCopy: ClipboardCopy,
  arrowLeft: ArrowLeft,
  briefcase: Briefcase,
  building: Building,
  filter: Filter,
  mapPin: MapPin,
  x: X,
  arrowUpRight: ArrowUpRight,
  chevronRight: ChevronRight,
  fileText: FileText,
  lightbulb: Lightbulb,
  wand2: Wand2,
}
